# Generated by Django 5.0.4 on 2024-04-24 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_dashboard', '0002_rename_name_category_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.BigIntegerField(max_length=10)),
                ('sku', models.CharField(editable=False, max_length=20, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('status', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='sales_images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.category')),
            ],
        ),
    ]
