# Generated by Django 5.0.4 on 2024-04-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='product_price',
            field=models.BigIntegerField(),
        ),
    ]
